### ISSUE TITLE
GitHub Page Images

### ISSUE THREAD

**Issue by bgonzalezbustamante** [jfabregalacoa/convencion_eficacia#1]
Muy interesante tu trabajo Jorge, felicitaciones. Me percaté de un pequeño problema estético en las imágenes cuando despliegas GitHub Page.

De momento el archivo MD está así: 

![Eficacia](https://github.com/jfabregalacoa/convencion_eficacia/blob/main/plots/eficacia_todos.png)

Si direccionas al raw file que sería, por ejemplo, https://raw.githubusercontent.com/jfabregalacoa/convencion_eficacia/main/plots/eficacia_todos.png debería solucionar el problema: 

![Eficacia](https://raw.githubusercontent.com/jfabregalacoa/convencion_eficacia/main/plots/eficacia_todos.png )

**Comment by jfabregalacoa** [comment]
Gracias por el comentario, Bastián. 
Ahora está corregido.
